services:
  postgres:
    image: postgres:16
    container_name: movieflix-db
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - movieflix-db-data:/var/lib/postgresql/data

volumes:
  movieflix-db-data:
