spring:
  application:
    name: movieflix
  
  # Conexao do Banco de Dados
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:movieflix}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # Avisa pro Hibernate qual dialeto de banco de dados vamos usar (Nesse caso: Postgres)
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Ativa migracoes
  flyway:
    enabled: true
